#!/usr/bin/env bash
# Displays information about subdomains
process_sub() {
    local domain="$1"
    local sub="$2"
    local fqdn="${sub}.${domain}"
    
    # Use Google's DNS (8.8.8.8) to bypass local resolver restrictions
    dig +nocmd +noall +answer "@8.8.8.8" "$fqdn" ANY | awk '
    NR==1 {
        # Handle different record types (A/CNAME/MX etc)
        type = $4
        dest = ($4 == "A") ? $5 : $NF  # $NF = last field for non-A records
        print "The subdomain", "'"$sub"'", "is a", type, "record and points to", dest
    }'
}

domain="$1"
subdomain="$2"

if [[ $# -eq 1 ]]; then
    for sub in www lb-01 web-01 web-02; do
        process_sub "$domain" "$sub"
    done
elif [[ $# -eq 2 ]]; then
    process_sub "$domain" "$subdomain"
fi
