#!/usr/bin/env bash
# Script to install and configure nginx
sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
