#!/usr/bin/env bash
# Script to config nginx server so /redirect_me is redirecting to another page
sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'

sudo bash -c 'cat > /var/www/html/index.html <<EOF
Hello World!
EOF'

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://linmihigo.github.io permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
