#!/usr/bin/env bash
# Installs load balancer
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg <<EOL
frontend lb_front_end
    bind *:80
    default_backend lb_back_end

backend lb_back_end
    balance roundrobin
    server 806515-web-01 100.25.41.202:80 check
    server 806515-web-02 100.25.205.60:80 check
EOL

sudo update-rc.d haproxy defaults
service haproxy start
