#!/usr/bin/env bash
# Displays contents of '/etc/passwd' but only displays username, user id
# and user home dir path
while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
