#!/usr/bin/env bash
# Configures an Ubuntu server that:
# - resolves 127.0.0.2 to localhost
# - resolves 8.8.8.8 to facebook.com

cp /etc/hosts ~/hosts.bak
echo "127.0.0.2		localhost" > ~/hosts.bak
echo "8.8.8.8		facebook.com" >> ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
